root: _site
vnu:
  - '--also-check-css'
  - '--also-check-svg'
ignore_re:
  - 'Attribute "Element "nobr" not allowed'
  - 'Element "nobr" not allowed'
  - 'The "align" attribute on the "img" element is obsolete'
  - '"color": Invalid RGB function'
blacklist:  # blocklint: pragma
  - 'bootstrap.min.css'
  - 'styles.min.css'
  - 'style.css'  # only needed for github actions build
  - 'chance-of-showers-plotly'
  - 'posts'
